services:
  second_hand:
    container_name: second_hand_bot
    build:
      context: .
      dockerfile: dockerfile
    restart: no
    networks:
      - proxy
    volumes:
      - ./bot:/workspace/bot
      - ./media:/workspace/media
      - ./config.ini:/workspace/config.ini:ro
      - ./pyproject.toml:/workspace/pyproject.toml:ro
    user: 1001:1001
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  proxy:
    external: true
    name: proxy
