[general]
storage_unavailable = "Хранилище недоступно, попробуйте позже."
storage_unavailable_support = "Хранилище недоступно, попробуйте позже или обратитесь к администратору."
no_submissions = "У вас пока нет отправленных заявок."
session_missing = "Сессия не найдена, отправьте /new"
photo_required = "Пожалуйста, отправьте фото позиции"
photo_save_error = "Ошибка сохранения фото, отправьте /new"
submission_success = "Заявка успешно отправлена! Спасибо."
submission_cancelled = "Заявка отменена"
navigation_denied = "Эта навигация недоступна."
placeholder = "—"

[start]
greeting = "Привет! Добро пожаловать."
new_instruction = "Чтобы отправить новую заявку, используйте команду /new."

[help]
text = "Доступные команды:\n/start — приветствие и краткая инструкция.\n/new — отправить новую заявку.\n/list — показать отправленные заявки.\n/cancel — отменить текущую заявку."
admin_header = "*Команды администратора:*"
admin_view = "/applications — просмотреть все заявки."
admin_broadcast = "/broadcast — отправить сообщение пользователям."
admin_history = "/broadcast_history — показать историю рассылок."
admin_scheduled = "/scheduled — показать запланированные рассылки."
super_admin_header = "*Команды суперадминистратора:*"
super_admin_add = "/addadmin — добавить нового администратора."
super_admin_remove = "/removeadmin — убрать права администратора."
super_admin_list = "/admins — список администраторов."

[list]
title = "*Ваши заявки:*"
entry_format = "{index}. {position} — отправлено {created_at}"
page_indicator = "Стр. {current}/{total}"
back_button = "← Назад"
forward_button = "Вперёд →"

[workflow]
position_prompt = "Введите *название позиции:*"
condition_prompt = "Выберите состояние:"
condition_used = "Б/У"
condition_new = "Новое"
photos_initial_prompt = "Отправьте 2–5 фото позиции"
photos_additional_required = "Фото получено. Ещё минимум одно фото."
photos_additional_optional = "Получено {count} фото. Если хотите добавить ещё — пришлите. Когда хватит, напишите '{keyword}'."
photos_max_prompt = "Максимум 5 фото получено. Теперь введите *размер:*"
skip_keyword = "далее"
size_prompt = "Введите *размер:*"
material_prompt = "Введите *материал:*"
description_prompt = "Введите *короткое описание:*"
price_prompt = "Введите *цену:*"
contacts_prompt = "Теперь оставьте ваши контакты (телефон, @username и т.д.)"
submission_received = "*Заявка получена!* Мы передадим её модератору."
summary_header = "*Новая заявка:*"
summary_position = "• *Позиция:* {value}"
summary_condition = "• *Состояние:* {value}"
summary_size = "• *Размер:* {value}"
summary_material = "• *Материал:* {value}"
summary_description = "• *Описание:* {value}"
summary_price = "• *Цена:* {value}"
summary_contacts = "• *Контакты:* {value}"

[admin]
not_authorized = "Эта команда доступна только администраторам."
super_admin_required = "Команда доступна только суперадминистраторам."
no_applications = "Заявок пока нет."
mode_time = "по времени"
mode_user = "по пользователям"
mode_time_button = "По времени"
mode_user_button = "По пользователям"
already_mode = "Этот режим уже активен."
navigation_end = "Других заявок нет."
user_label_username = "@{username}"
user_label_numbered = "Пользователь №{number} (ID {user_id})"
photo_missing = "нет"
view_caption = "<b>Заявка {index}/{total}</b>\n<b>Режим:</b> {mode}\n<b>Пользователь:</b> {user_label}\n<b>Отправлено:</b> {created_at}\n<b>Позиция:</b> {position}\n<b>Состояние:</b> {condition}\n<b>Размер:</b> {size}\n<b>Материал:</b> {material}\n<b>Описание:</b> {description}\n<b>Цена:</b> {price}\n<b>Контакты:</b> {contacts}\n<b>Фото:</b> {photo_count}"
add_prompt = "Отправьте идентификатор пользователя, которому нужно дать права администратора."
add_invalid = "Пожалуйста, отправьте числовой идентификатор пользователя."
add_success = "Пользователь {user_id} теперь администратор."
add_already = "Пользователь {user_id} уже является администратором."
remove_prompt = "Отправьте идентификатор администратора, которого нужно удалить."
remove_success = "Пользователь {user_id} больше не администратор."
remove_missing = "Пользователь {user_id} не является администратором."
remove_super_admin = "Нельзя изменить права суперадминистратора."
cancelled = "Действие отменено."
broadcast_audience_prompt = "Выберите аудиторию рассылки."
broadcast_audience_all = "Все активные пользователи"
broadcast_audience_recent = "Пользователи с заявками за последний месяц"
broadcast_message_prompt = "Отправьте текст сообщения для рассылки."
broadcast_preview_title = "Предпросмотр рассылки:"
broadcast_preview_controls = "Выберите действие:"
broadcast_send_now = "Отправить сейчас"
broadcast_schedule = "Запланировать"
broadcast_cancel = "Отмена"
broadcast_scheduled_prompt = "Введите дату и время по Москве в формате ГГГГ-ММ-ДД ЧЧ:ММ."
broadcast_schedule_invalid = "Не удалось распознать дату. Проверьте формат и укажите время в будущем."
broadcast_confirm = "Рассылка для аудитории \"{audience}\" ({count} получателей).\n{schedule_info}\nПодтвердите отправку?"
broadcast_schedule_info_now = "Отправка начнётся сразу после подтверждения."
broadcast_schedule_info_time = "Запланированное время: {time}."
broadcast_confirm_button = "Подтвердить"
broadcast_confirm_cancel_button = "Отмена"
broadcast_no_recipients = "Для выбранной аудитории не найдено получателей."
broadcast_cancelled = "Рассылка отменена."
broadcast_started = "Рассылка запущена. Идентификатор: {broadcast_id}."
broadcast_scheduled = "Рассылка запланирована на {time}. Идентификатор: {broadcast_id}."
scheduled_header = "*Запланированные рассылки:*"
scheduled_empty = "Нет активных запланированных рассылок."
scheduled_entry = "{index}. {time} — аудитория \"{audience}\" ({count} получателей). ID: {broadcast_id}"
history_header = "*История рассылок (последние 10):*"
history_empty = "Рассылок ещё не было."
history_entry = "{index}. {created_at} — {status}, аудитория \"{audience}\" ({count} получателей). Успешно: {success}, ошибки: {failed}. ID: {broadcast_id}{schedule_info}{completed_info}"
history_schedule_suffix = " Запланировано на {time}."
history_completed_suffix = " Завершено: {time}."
history_status_queued = "в очереди"
history_status_scheduled = "запланирована"
history_status_running = "в процессе"
history_status_sent = "отправлена"
history_status_unknown = "статус {status}"
roster_header = "*Текущие администраторы:*"
roster_super_admins = "*Суперадминистраторы:*"
roster_admins = "*Администраторы:*"
roster_entry = "{index}. ID `{user_id}`"
roster_empty = "нет записей"
