name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --group dev --frozen

      - name: Ruff format
        run: uv run ruff format --check .

      - name: Ruff lint
        run: uv run ruff check .

      - name: Run tests
        if: ${{ hashFiles('test/**/*.py') != '' }}
        run: uv run pytest
